easy_admin:
   list:
        item_permission: 'ROLE_ADMIN'
   entities:
       Catégorie:
        class: App\Entity\Categorie
        list:
          item_permission: 'ROLE_ADMIN'
       Commentaire:
        class: App\Entity\Commentaire
        list:
          item_permission: 'ROLE_ADMIN'
       User:
        class: App\Entity\User
        list:
          item_permission: 'ROLE_ADMIN'
       Recette:
        class: App\Entity\Recette
        list:
          item_permission: ['ROLE_ADMIN','ROLE_EDITOR']
       Ingredient:
        class: App\Entity\Ingredient
        list:
          item_permission: ['ROLE_ADMIN','ROLE_EDITOR']