easy_admin:
   entities:
       # List the entity class name you want to manage
       - App\Entity\Categorie
       - App\Entity\Commentaire
       - App\Entity\User
       - App\Entity\Recette
       - App\Entity\Ingredient
